### PR TITLE
Search Input: Add hover effect

### PR DESCRIPTION
**Pull request by lexahall**
This applies the same effect that was currently applied to `:focus` to `:hover` as well.

### regular:
image

### hover/focus:
image

## QA 
- go to https://deploy-preview-34--toolbox.netlify.com/#searchinput and ensure that the drop shadow adjusts when you hover over or click on `<SearchInput>`
- make sure that the hover effect is not applied to the disabled input

### CODE REVIEW

**Comment by colebemis** [comment]
We need to make sure that the hover effect doesn't happen when the input is disabled.

**Comment by colebemis** [comment]
CR 👍

**Comment by k0rvusk0r4x** [comment]
Went to https://deploy-preview-34--toolbox.netlify.com/#searchinput and played with the search boxes.

Noted:
- Shadow affect appears when hovering over active search boxes.
- Shadow affect does not appear when hovering over disabled search boxes.
- Shadow affect stays when focus is on a particular search box whether hovering over it or not.

QA 😺

**Comment by k0rvusk0r4x** [comment]
QA 🐖:back:

**Comment by colebemis** [comment]
CR 🌮

**Comment by copperwall** [comment]
CR 🔥

**Pull request merged**
