### PR TITLE
Ratings: Add Stars Component

### PR DESCRIPTION
**Pull request by tvillarete**
kapture 2018-08-15 at 19 53 51
## Details
We're adding a product review system to iFixit. In order to build out the system, we first need a couple components. This pull adds a reusable and customizable star ratings component.

## Background
Part of https://github.com/iFixit/ifixit/issues/25326

cc: @kimarre

### CODE REVIEW

**Comment by sterlinghirsh** [comment]
CR :zap: but dev_block :zap: on something wrong with the test

**Comment by tvillarete** [comment]
I looked around and fiddled with stuff, but I don't know enough about our testing infrastructure to understand why it's hanging every time I try to commit. I'll be sure to add it at a later point, but for now, we just need to get this component merged.

**Comment by tvillarete** [comment]
Pretty @danielbeardsley and I found a solution to the failing tests. It requires a bit of "hacky" `id` manipulation within the test file to create a snapshot that isn't randomized each time, but it gets the job done. un_dev_block 🚦

**Comment by sterlinghirsh** [comment]
CR :zap:

**Comment by cdcline** [comment]
CR 👍

**Pull request merged**
